// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crawl_jobs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCrawlJob = `-- name: CreateCrawlJob :one
INSERT INTO crawl_jobs (id, created_at, updated_at, user_id, seed_url, status, max_depth, max_pages)
VALUES ($1, $2, $3, $4, $5, 'pending', $6, $7)
RETURNING id, created_at, updated_at, user_id, seed_url, status, max_depth, max_pages, pages_crawled, started_at, finished_at, error_msg, discovered_feeds
`

type CreateCrawlJobParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	SeedUrl   string
	MaxDepth  int32
	MaxPages  int32
}

func (q *Queries) CreateCrawlJob(ctx context.Context, arg CreateCrawlJobParams) (CrawlJob, error) {
	row := q.db.QueryRowContext(ctx, createCrawlJob,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.SeedUrl,
		arg.MaxDepth,
		arg.MaxPages,
	)
	var i CrawlJob
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.SeedUrl,
		&i.Status,
		&i.MaxDepth,
		&i.MaxPages,
		&i.PagesCrawled,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMsg,
		&i.DiscoveredFeeds,
	)
	return i, err
}

const getCrawlJobByID = `-- name: GetCrawlJobByID :one
SELECT id, created_at, updated_at, user_id, seed_url, status, max_depth, max_pages, pages_crawled, started_at, finished_at, error_msg, discovered_feeds FROM crawl_jobs WHERE id = $1
`

func (q *Queries) GetCrawlJobByID(ctx context.Context, id uuid.UUID) (CrawlJob, error) {
	row := q.db.QueryRowContext(ctx, getCrawlJobByID, id)
	var i CrawlJob
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.SeedUrl,
		&i.Status,
		&i.MaxDepth,
		&i.MaxPages,
		&i.PagesCrawled,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMsg,
		&i.DiscoveredFeeds,
	)
	return i, err
}

const getCrawlJobsByUserID = `-- name: GetCrawlJobsByUserID :many
SELECT id, created_at, updated_at, user_id, seed_url, status, max_depth, max_pages, pages_crawled, started_at, finished_at, error_msg, discovered_feeds FROM crawl_jobs WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetCrawlJobsByUserID(ctx context.Context, userID uuid.UUID) ([]CrawlJob, error) {
	rows, err := q.db.QueryContext(ctx, getCrawlJobsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrawlJob
	for rows.Next() {
		var i CrawlJob
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.SeedUrl,
			&i.Status,
			&i.MaxDepth,
			&i.MaxPages,
			&i.PagesCrawled,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMsg,
			&i.DiscoveredFeeds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCrawlJobDiscoveredFeeds = `-- name: UpdateCrawlJobDiscoveredFeeds :exec
UPDATE crawl_jobs SET discovered_feeds = $2, updated_at = NOW() WHERE id = $1
`

type UpdateCrawlJobDiscoveredFeedsParams struct {
	ID              uuid.UUID
	DiscoveredFeeds string
}

func (q *Queries) UpdateCrawlJobDiscoveredFeeds(ctx context.Context, arg UpdateCrawlJobDiscoveredFeedsParams) error {
	_, err := q.db.ExecContext(ctx, updateCrawlJobDiscoveredFeeds, arg.ID, arg.DiscoveredFeeds)
	return err
}

const updateCrawlJobFailed = `-- name: UpdateCrawlJobFailed :one
UPDATE crawl_jobs
SET status = 'failed', finished_at = NOW(), updated_at = NOW(), error_msg = $2
WHERE id = $1
RETURNING id, created_at, updated_at, user_id, seed_url, status, max_depth, max_pages, pages_crawled, started_at, finished_at, error_msg, discovered_feeds
`

type UpdateCrawlJobFailedParams struct {
	ID       uuid.UUID
	ErrorMsg sql.NullString
}

func (q *Queries) UpdateCrawlJobFailed(ctx context.Context, arg UpdateCrawlJobFailedParams) (CrawlJob, error) {
	row := q.db.QueryRowContext(ctx, updateCrawlJobFailed, arg.ID, arg.ErrorMsg)
	var i CrawlJob
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.SeedUrl,
		&i.Status,
		&i.MaxDepth,
		&i.MaxPages,
		&i.PagesCrawled,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMsg,
		&i.DiscoveredFeeds,
	)
	return i, err
}

const updateCrawlJobFinished = `-- name: UpdateCrawlJobFinished :one
UPDATE crawl_jobs
SET status = 'completed', finished_at = NOW(), updated_at = NOW(), pages_crawled = $2
WHERE id = $1
RETURNING id, created_at, updated_at, user_id, seed_url, status, max_depth, max_pages, pages_crawled, started_at, finished_at, error_msg, discovered_feeds
`

type UpdateCrawlJobFinishedParams struct {
	ID           uuid.UUID
	PagesCrawled int32
}

func (q *Queries) UpdateCrawlJobFinished(ctx context.Context, arg UpdateCrawlJobFinishedParams) (CrawlJob, error) {
	row := q.db.QueryRowContext(ctx, updateCrawlJobFinished, arg.ID, arg.PagesCrawled)
	var i CrawlJob
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.SeedUrl,
		&i.Status,
		&i.MaxDepth,
		&i.MaxPages,
		&i.PagesCrawled,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMsg,
		&i.DiscoveredFeeds,
	)
	return i, err
}

const updateCrawlJobProgress = `-- name: UpdateCrawlJobProgress :exec
UPDATE crawl_jobs SET pages_crawled = $2, updated_at = NOW() WHERE id = $1
`

type UpdateCrawlJobProgressParams struct {
	ID           uuid.UUID
	PagesCrawled int32
}

func (q *Queries) UpdateCrawlJobProgress(ctx context.Context, arg UpdateCrawlJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateCrawlJobProgress, arg.ID, arg.PagesCrawled)
	return err
}

const updateCrawlJobStarted = `-- name: UpdateCrawlJobStarted :one
UPDATE crawl_jobs
SET status = 'running', started_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, user_id, seed_url, status, max_depth, max_pages, pages_crawled, started_at, finished_at, error_msg, discovered_feeds
`

func (q *Queries) UpdateCrawlJobStarted(ctx context.Context, id uuid.UUID) (CrawlJob, error) {
	row := q.db.QueryRowContext(ctx, updateCrawlJobStarted, id)
	var i CrawlJob
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.SeedUrl,
		&i.Status,
		&i.MaxDepth,
		&i.MaxPages,
		&i.PagesCrawled,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMsg,
		&i.DiscoveredFeeds,
	)
	return i, err
}
