// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPage = `-- name: CreatePage :exec
INSERT INTO pages (id, created_at, crawl_job_id, url, status_code, depth, page_rank, inbound_count, is_redirect, redirect_to)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (crawl_job_id, url) DO NOTHING
`

type CreatePageParams struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	CrawlJobID   uuid.UUID
	Url          string
	StatusCode   sql.NullInt32
	Depth        int32
	PageRank     float64
	InboundCount int32
	IsRedirect   bool
	RedirectTo   sql.NullString
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) error {
	_, err := q.db.ExecContext(ctx, createPage,
		arg.ID,
		arg.CreatedAt,
		arg.CrawlJobID,
		arg.Url,
		arg.StatusCode,
		arg.Depth,
		arg.PageRank,
		arg.InboundCount,
		arg.IsRedirect,
		arg.RedirectTo,
	)
	return err
}

const getPagesByCrawlJob = `-- name: GetPagesByCrawlJob :many
SELECT id, created_at, crawl_job_id, url, status_code, depth, page_rank, inbound_count, is_redirect, redirect_to FROM pages WHERE crawl_job_id = $1 ORDER BY page_rank DESC
`

func (q *Queries) GetPagesByCrawlJob(ctx context.Context, crawlJobID uuid.UUID) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, getPagesByCrawlJob, crawlJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CrawlJobID,
			&i.Url,
			&i.StatusCode,
			&i.Depth,
			&i.PageRank,
			&i.InboundCount,
			&i.IsRedirect,
			&i.RedirectTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
