// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_links.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPageLink = `-- name: CreatePageLink :exec
INSERT INTO page_links (id, crawl_job_id, from_url, to_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (crawl_job_id, from_url, to_url) DO NOTHING
`

type CreatePageLinkParams struct {
	ID         uuid.UUID
	CrawlJobID uuid.UUID
	FromUrl    string
	ToUrl      string
}

func (q *Queries) CreatePageLink(ctx context.Context, arg CreatePageLinkParams) error {
	_, err := q.db.ExecContext(ctx, createPageLink,
		arg.ID,
		arg.CrawlJobID,
		arg.FromUrl,
		arg.ToUrl,
	)
	return err
}

const getPageLinksByCrawlJob = `-- name: GetPageLinksByCrawlJob :many
SELECT id, crawl_job_id, from_url, to_url FROM page_links WHERE crawl_job_id = $1
`

func (q *Queries) GetPageLinksByCrawlJob(ctx context.Context, crawlJobID uuid.UUID) ([]PageLink, error) {
	rows, err := q.db.QueryContext(ctx, getPageLinksByCrawlJob, crawlJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageLink
	for rows.Next() {
		var i PageLink
		if err := rows.Scan(
			&i.ID,
			&i.CrawlJobID,
			&i.FromUrl,
			&i.ToUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
